### ISSUE TITLE
Change output when inferencing to over 256x256 and to use rectangular aspect ratio?

### ISSUE THREAD

**Issue by stanleyshly** [carolineec/EverybodyDanceNow#14]
I'm training with `python3 train_fullts.py \
--name ./model_global/ \
--dataroot ./dataset/train/  \
--checkpoints_dir ./checkpoints/ \
--loadSize 512 \
--no_instance \
--no_flip \
--tf_log \
--label_nc 6 \
--resize_or_crop scale_width \
--save_latest_freq 100 \
`
and inferencings with `python3 test_fullts.py \
--name model_global \
--dataroot ./dataset/test/ \
--checkpoints_dir ./checkpoints/ \
--results_dir ./result/ \
--loadSize 512 \
--no_instance \
--how_many 10000 \
--label_nc 6 \
--aspect_ratio 2.0 \`, but when inferencing, the result is a square 256x256, no matter how I change the output. How do I output in a non square aspect ratio and at a resolution greater than 256?

**Comment by justinjohn0306** [comment]
Find the file "util.py" in folder "util", and comment out " image_pil = image_pil.resize((256,256), Image.ANTIALIAS) " in "save_image" function . ( Or just change size you want . )

**Comment by stanleyshly** [comment]
This works! Thank you.
