### ISSUE TITLE
Could you please release the pretrained model?

### ISSUE THREAD

**Issue by quqixun** [carolineec/EverybodyDanceNow#18]

**Comment by alamayreh** [comment]
Folks, if you have the pretrained models, could you please share them?

**Comment by hshreeshail** [comment]
Hi @quqixun, why did you close the issue. Did you find the pretrained model?

**Comment by alamayreh** [comment]
Hi, we didn't find the pre-trained model. 

However, I can point you to this paper : 

https://assets.researchsquare.com/files/rs-1858607/v1_covered.pdf?c=1658425842

Best regards
