### ISSUE TITLE
Can you share the pytorch version ?

### ISSUE THREAD

**Issue by kaswani29** [carolineec/EverybodyDanceNow#4]
I am getting this error while training subject1 local state and subject2 global stage:

`AttributeError: 'int' object has no attribute 'numel'`

**Comment by ipwefpo** [comment]
Hi,
in my case these version should work :
--python3.6 
--torch 1.6.0+cu101
--torchvision 0.7.0+cu101
--tensorflow 1.15.0 ( if you install a newer version, some function is not compatible . )

**Comment by tyrink** [comment]
> Hi,
> in my case these version should work :
> --python3.6
> --torch 1.6.0+cu101
> --torchvision 0.7.0+cu101
> --tensorflow 1.15.0 ( if you install a newer version, some function is not compatible . )

Have you ever implemented this work? If so,  how  did you process the input video and how to create the folder path? I just cannot figure it out. Thanks!

**Comment by ipwefpo** [comment]
> > Hi,
> > in my case these version should work :
> > --python3.6
> > --torch 1.6.0+cu101
> > --torchvision 0.7.0+cu101
> > --tensorflow 1.15.0 ( if you install a newer version, some function is not compatible . )
> 
> Have you ever implemented this work? If so, how did you process the input video and how to create the folder path? I just cannot figure it out. Thanks!

Hi,

Source & Target video need to use openpose to get keypoint & frames, folder path follow the parameters instruction in files you want to execute . 

I talk about my experience briefly at #5,  hope that can help .

**Comment by tyrink** [comment]
> > > Hi,
> > > in my case these version should work :
> > > --python3.6
> > > --torch 1.6.0+cu101
> > > --torchvision 0.7.0+cu101
> > > --tensorflow 1.15.0 ( if you install a newer version, some function is not compatible . )
> > 
> > 
> > Have you ever implemented this work? If so, how did you process the input video and how to create the folder path? I just cannot figure it out. Thanks!
> 
> Hi,
> 
> Source & Target video need to use openpose to get keypoint & frames, folder path follow the parameters instruction in files you want to execute .
> 
> I talk about my experience briefly at #5, hope that can help .

Hi, thanks a lot for your reply!  
I had noticed your answer at #5, but did you use the body_135 estimation model or just the usual openpose? And which form did you choose to store the keypoints file? .json?

**Comment by ipwefpo** [comment]
> > > > Hi,
> > > > in my case these version should work :
> > > > --python3.6
> > > > --torch 1.6.0+cu101
> > > > --torchvision 0.7.0+cu101
> > > > --tensorflow 1.15.0 ( if you install a newer version, some function is not compatible . )
> > > 
> > > 
> > > Have you ever implemented this work? If so, how did you process the input video and how to create the folder path? I just cannot figure it out. Thanks!
> > 
> > 
> > Hi,
> > Source & Target video need to use openpose to get keypoint & frames, folder path follow the parameters instruction in files you want to execute .
> > I talk about my experience briefly at #5, hope that can help .
> 
> Hi, thanks a lot for your reply!
> I had noticed your answer at #5, but did you use the body_135 estimation model or just the usual openpose? And which form did you choose to store the keypoints file? .json?

Hi,
I use body_25 ( it should have butter choice about estimation model, you can try on this part . ) to get keypoints file, don't forget the parameters like --hands, --face, and save them as .yaml file .
I think .json should work too, just care for the file name .

**Comment by tyrink** [comment]
> > > > > Hi,
> > > > > in my case these version should work :
> > > > > --python3.6
> > > > > --torch 1.6.0+cu101
> > > > > --torchvision 0.7.0+cu101
> > > > > --tensorflow 1.15.0 ( if you install a newer version, some function is not compatible . )
> > > > 
> > > > 
> > > > Have you ever implemented this work? If so, how did you process the input video and how to create the folder path? I just cannot figure it out. Thanks!
> > > 
> > > 
> > > Hi,
> > > Source & Target video need to use openpose to get keypoint & frames, folder path follow the parameters instruction in files you want to execute .
> > > I talk about my experience briefly at #5, hope that can help .
> > 
> > 
> > Hi, thanks a lot for your reply!
> > I had noticed your answer at #5, but did you use the body_135 estimation model or just the usual openpose? And which form did you choose to store the keypoints file? .json?
> 
> Hi,
> I use body_25 ( it should have butter choice about estimation model, you can try on this part . ) to get keypoints file, don't forget the parameters like --hands, --face, and save them as .yaml file .
> I think .json should work too, just care for the file name .

Thanks for your answer, which helps me a lot. 
Have a nice day!

**Comment by niravbeni** [comment]
> > > Hi,
> > > in my case these version should work :
> > > --python3.6
> > > --torch 1.6.0+cu101
> > > --torchvision 0.7.0+cu101
> > > --tensorflow 1.15.0 ( if you install a newer version, some function is not compatible . )
> > 
> > 
> > Have you ever implemented this work? If so, how did you process the input video and how to create the folder path? I just cannot figure it out. Thanks!
> 
> Hi,
> 
> Source & Target video need to use openpose to get keypoint & frames, folder path follow the parameters instruction in files you want to execute .
> 
> I talk about my experience briefly at #5, hope that can help .

Hi, 

I was able to train the model, but when I'm trying to test to get the results, I can't seem to get the 1024 x 512 sizer results - it just renders at 256 x 256 for some reason. Were you able to get good results?

**Comment by ipwefpo** [comment]
> > > > Hi,
> > > > in my case these version should work :
> > > > --python3.6
> > > > --torch 1.6.0+cu101
> > > > --torchvision 0.7.0+cu101
> > > > --tensorflow 1.15.0 ( if you install a newer version, some function is not compatible . )
> > > 
> > > 
> > > Have you ever implemented this work? If so, how did you process the input video and how to create the folder path? I just cannot figure it out. Thanks!
> > 
> > 
> > Hi,
> > Source & Target video need to use openpose to get keypoint & frames, folder path follow the parameters instruction in files you want to execute .
> > I talk about my experience briefly at #5, hope that can help .
> 
> Hi,
> 
> I was able to train the model, but when I'm trying to test to get the results, I can't seem to get the 1024 x 512 sizer results - it just renders at 256 x 256 for some reason. Were you able to get good results?

Hi,
Find the file "util.py" in folder "util", and comment out  " image_pil = image_pil.resize((256,256), Image.ANTIALIAS) " in "save_image" function . ( Or just change size you want . )
